import { useEffect, useState } from 'react';
import { NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { CalendarClock, CheckCircle2, LogOut, Mail, Plus, RefreshCw, Search, Slack as SlackIcon, Upload } from 'lucide-react';
import { toast } from 'sonner';
import { api } from './services/api';
import type { EmailJob, Sender, Slack, User } from './types';

const apiUrl = import.meta.env.VITE_API_URL;
const formatDate = (value: string) => new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });

function Login() {
  return <main className="login"><div className="login-art"><span className="eyebrow">EMAIL SCHEDULER / OPERATIONS</span><h1>Every send,<br /><i>considered.</i></h1><p>Schedule thoughtful outreach at a pace your audience can respect.</p></div><section className="login-panel"><div className="mark"><Mail size={18} /> ES</div><h2>Welcome back</h2><p className="muted">Sign in to your sending workspace.</p><a className="google" href={`${apiUrl}/auth/google`}>Continue with Google <span>{'->'}</span></a><small>Configure Google OAuth credentials in the backend environment before signing in.</small></section></main>;
}

function Shell({ user, slack, senders, onLogout, reload }: { user: User; slack: Slack; senders: Sender[]; onLogout: () => void; reload: () => void }) {
  const [compose, setCompose] = useState(false);
  return <div className="app-shell"><aside><div className="brand"><span className="brand-icon">E</span><span>email scheduler</span></div><div className="workspace"><span className="avatar">{user.name[0]}</span><div><b>{user.name}</b><small>{user.email}</small></div></div><nav><NavLink to="/" end><CalendarClock size={17} /> Scheduled</NavLink><NavLink to="/sent"><CheckCircle2 size={17} /> Sent</NavLink></nav><div className="aside-bottom"><div className={`slack-state ${slack?.connected ? 'active' : ''}`}><SlackIcon size={16} /><span>Slack {slack?.connected ? 'connected' : 'not connected'}</span></div>{slack?.connected ? <button className="text-button" onClick={() => api.post('/slack/disconnect').then(reload)}><SlackIcon size={15} /> Disconnect Slack</button> : <a className="text-button" href={`${apiUrl}/slack/connect`}><SlackIcon size={15} /> Connect Slack</a>}<button className="text-button" onClick={onLogout}><LogOut size={15} /> Log out</button></div></aside><main className="main"><header><div><span className="eyebrow">EMAIL SCHEDULER / WORKSPACE</span><h1>Campaign control room</h1></div><button className="primary" onClick={() => setCompose(true)}><Plus size={18} /> Compose new email</button></header><Routes><Route path="/" element={<EmailTable mode="scheduled" onCompose={() => setCompose(true)} />} /><Route path="/sent" element={<EmailTable mode="sent" onCompose={() => setCompose(true)} />} /></Routes></main>{compose && <Compose senders={senders} close={() => setCompose(false)} />}</div>;
}

function EmailTable({ mode, onCompose }: { mode: 'scheduled' | 'sent'; onCompose: () => void }) {
  const [jobs, setJobs] = useState<EmailJob[]>([]); const [query, setQuery] = useState('');
  const load = () => api.get(`/emails/${query ? `search?q=${encodeURIComponent(query)}` : mode}`).then(response => setJobs(response.data.emails)).catch(() => toast.error('Could not load emails'));
  useEffect(() => { load(); }, [mode]);
  return <section className="content"><div className="toolbar"><div><h2>{mode === 'scheduled' ? 'Scheduled emails' : 'Sent history'}</h2><p className="muted">{mode === 'scheduled' ? 'Queued outreach, ordered by send time.' : 'A record of every delivery attempt.'}</p></div><div className="actions"><label className="search"><Search size={16} /><input placeholder="Search emails" value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => event.key === 'Enter' && load()} /></label><button className="icon-button" title="Refresh" onClick={load}><RefreshCw size={17} /></button></div></div><div className="table-wrap"><table><thead><tr><th>Recipient</th><th>Subject</th><th>{mode === 'scheduled' ? 'Scheduled' : 'Sent'} time</th><th>Status</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td className="recipient">{job.recipientEmail}</td><td>{job.subject}</td><td>{formatDate(mode === 'scheduled' ? job.scheduledAt : (job.sentAt ?? job.scheduledAt))}</td><td><span className={`badge ${job.status}`}>{job.status}</span></td></tr>)}</tbody></table>{jobs.length === 0 && <div className="empty"><Mail size={28} /><h3>No emails here yet</h3><p className="muted">Compose a campaign to see your sending queue.</p><button className="secondary" onClick={onCompose}>Start a campaign</button></div>}</div></section>;
}

function Compose({ senders, close }: { senders: Sender[]; close: () => void }) {
  const [file, setFile] = useState<File>(); const [form, setForm] = useState({ senderId: senders[0]?.id ?? '', subject: '', body: '', startTime: '', delayBetweenEmails: '10', hourlyLimit: '100' });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return toast.error('Upload a recipient CSV first'); const data = new FormData(); Object.entries(form).forEach(([key, value]) => data.append(key, value)); data.append('file', file); try { await api.post('/campaigns', data); toast.success('Campaign scheduled'); close(); } catch (error: any) { toast.error(error.response?.data?.error ?? 'Could not schedule campaign'); } };
  return <div className="overlay"><form className="modal" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">NEW CAMPAIGN</span><h2>Compose email</h2></div><button type="button" className="close" onClick={close}>x</button></div><label>Sender<select required value={form.senderId} onChange={event => setForm({ ...form, senderId: event.target.value })}><option value="">Select a sender</option>{senders.map(sender => <option key={sender.id} value={sender.id}>{sender.name} · {sender.email}</option>)}</select></label><label>Subject<input required value={form.subject} onChange={event => setForm({ ...form, subject: event.target.value })} placeholder="A clear subject line" /></label><label>Body<textarea required rows={6} value={form.body} onChange={event => setForm({ ...form, body: event.target.value })} placeholder="Write your message..." /></label><label className="file-drop"><Upload size={20} /><span>{file?.name ?? 'Upload a CSV of recipients'}</span><input required type="file" accept=".csv,.txt" onChange={event => setFile(event.target.files?.[0])} /></label><div className="field-grid"><label>Start time<input required type="datetime-local" value={form.startTime} onChange={event => setForm({ ...form, startTime: event.target.value })} /></label><label>Delay (seconds)<input required type="number" min="0" value={form.delayBetweenEmails} onChange={event => setForm({ ...form, delayBetweenEmails: event.target.value })} /></label><label>Hourly limit<input required type="number" min="1" value={form.hourlyLimit} onChange={event => setForm({ ...form, hourlyLimit: event.target.value })} /></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit"><CalendarClock size={17} /> Schedule emails</button></div></form></div>;
}

export default function App() { const [user, setUser] = useState<User>(); const [slack, setSlack] = useState<Slack>(null); const [senders, setSenders] = useState<Sender[]>([]); const navigate = useNavigate(); const reload = () => { api.get('/slack/status').then(response => setSlack(response.data.slack)); api.get('/senders').then(response => setSenders(response.data.senders)); }; useEffect(() => { api.get('/auth/me').then(response => { setUser(response.data.user); reload(); }).catch(() => undefined); }, []); if (!user) return <Login />; return <Shell user={user} slack={slack} senders={senders} reload={reload} onLogout={() => api.post('/auth/logout').then(() => { setUser(undefined); navigate('/'); })} />; }
